language: go
go:
  - 1.13.x

go_import_path: github.com/Eun/yaegi-template

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)